#!/bin/bash

#parametry
ROZ="0"
DNI=0
NAZ="0"

while getopts ":n:m:a:" opt;
do
  case $opt in
 
    -n)
	echo "Wywołano parametr -n" >&2
	ROZ=$OPTARG;;
 
    -m)
	echo "Wywołano parametr -m" >&2
	DNI=$OPTARG;;
 
    -a)
	echo "Wywołano parametr -a" >&2
	NAZ=$OPTARG;;
 
    \?)
	echo "Nieprawodłowy parametr: -$OPTARG" >&2;;
    :)
	echo "Opcja -$OPTARG wymaga podania argumentu" >&2
	exit 1;;
    
  esac
done

if [ $ROZ = "0" ];
then
    echo "Wprowadź nazwę pliku lub rozszerzenie"
    read NEW_NAME
    ROZ=$NEW_NAME
    #echo "$ROZ"
fi

if [ $DNI -eq 0 ];
then
    echo "Wprowadź liczbę dni od ostaniej modyfikacji"
    read NEW_NUMBER
    DNI=$NEW_NUMBER
    #echo "$DNI"
fi

if [ $NAZ = "0" ];
then
    echo "Wprowadz nazwę archiwum"
    read NEW_NAME
    NAZ=$NEW_NAME
    #echo "$NAZ"
fi

echo Znalezione pliki:
find . -name "$ROZ" -mtime -$DNI -print > lista_plikow
tar -cvf $NAZ.tar -T lista_plikow
